strictness: veryhigh
max-line-length: 110
doc-warnings: True

pylint:
  disable:
    - wrong-import-order
    - too-many-arguments
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - too-many-nested-blocks
    - too-few-public-methods

pycodestyle:
  options:
    max-line-length: 110
  disable:
    - E203 # whitespace before ':'

pydocstyle:
  disable:
    - D203 # 1 blank line required before class docstring (found 0)

bandit:
  run: true

mypy:
  run: true
  options:
    python-version: 3.8
    ignore-missing-imports: True
    warn:
      - redundant-casts
      - unused-ignores
    check:
      - untyped-defs

mccabe:
  run: false
